//
//  LibretroKeyboardCode.m
//  Libretro
//
//  Created by Daiuno on 2026/1/24.
//  Copyright © 2026 Manic EMU. All rights reserved.
//

#import "LibretroKeyboardCode.h"
#include "../../../libretro-common/include/libretro.h"

@interface LibretroKeyboardCode()

@property(nonatomic, copy) NSString *label;
@property(assign) unsigned code;

@end

@implementation LibretroKeyboardCode

+ (NSArray<NSString *> *)getAllKeyboarLabels {
    return @[
        @"1",
        @"2",
        @"3",
        @"4",
        @"5",
        @"6",
        @"7",
        @"8",
        @"9",
        @"0",
        @"a",
        @"b",
        @"c",
        @"d",
        @"e",
        @"f",
        @"g",
        @"h",
        @"i",
        @"j",
        @"k",
        @"l",
        @"m",
        @"n",
        @"o",
        @"p",
        @"q",
        @"r",
        @"s",
        @"t",
        @"u",
        @"v",
        @"w",
        @"x",
        @"y",
        @"z",
        @"f1",
        @"f2",
        @"f3",
        @"f4",
        @"f5",
        @"f6",
        @"f7",
        @"f8",
        @"f9",
        @"f10",
        @"f11",
        @"f12",
        @"f13",
        @"f14",
        @"f15",
        @"escape",
        @"backspace",
        @"tab",
        @"return",
        @"space",
        @"delete",
        @"insert",
        @"home",
        @"end",
        @"pageup",
        @"pagedown",
        @"print",
        @"scrolllock",
        @"pause",
        @"numlock",
        @"capslock",
        @"up",
        @"down",
        @"left",
        @"right",
        @"comma",
        @"period",
        @"slash",
        @"semicolon",
        @"quote",
        @"leftbracket",
        @"rightbracket",
        @"backslash",
        @"minus",
        @"equals",
        @"backquote",
        @"plus",
        @"asterisk",
        @"bar",
        @"oem102",
        @"shift",
        @"lshift",
        @"rshift",
        @"ctrl",
        @"lctrl",
        @"rctrl",
        @"alt",
        @"lalt",
        @"ralt",
        @"meta",
        @"lmeta",
        @"rmeta",
        @"kp0",
        @"kp1",
        @"kp2",
        @"kp3",
        @"kp4",
        @"kp5",
        @"kp6",
        @"kp7",
        @"kp8",
        @"kp9",
        @"kpperiod",
        @"kpdivide",
        @"kpmultiply",
        @"kpminus",
        @"kpplus",
        @"kpenter",
        @"kpequals"
    ];
}

+ (NSDictionary<NSString *, NSNumber *> *)codeMap {
    static NSDictionary<NSString *, NSNumber *> *map;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        map = @{
            @"0": @(RETROK_0),
            @"1": @(RETROK_1),
            @"2": @(RETROK_2),
            @"3": @(RETROK_3),
            @"4": @(RETROK_4),
            @"5": @(RETROK_5),
            @"6": @(RETROK_6),
            @"7": @(RETROK_7),
            @"8": @(RETROK_8),
            @"9": @(RETROK_9),
            @"a": @(RETROK_a),
            @"b": @(RETROK_b),
            @"c": @(RETROK_c),
            @"d": @(RETROK_d),
            @"e": @(RETROK_e),
            @"f": @(RETROK_f),
            @"g": @(RETROK_g),
            @"h": @(RETROK_h),
            @"i": @(RETROK_i),
            @"j": @(RETROK_j),
            @"k": @(RETROK_k),
            @"l": @(RETROK_l),
            @"m": @(RETROK_m),
            @"n": @(RETROK_n),
            @"o": @(RETROK_o),
            @"p": @(RETROK_p),
            @"q": @(RETROK_q),
            @"r": @(RETROK_r),
            @"s": @(RETROK_s),
            @"t": @(RETROK_t),
            @"u": @(RETROK_u),
            @"v": @(RETROK_v),
            @"w": @(RETROK_w),
            @"x": @(RETROK_x),
            @"y": @(RETROK_y),
            @"z": @(RETROK_z),
            @"f1": @(RETROK_F1),
            @"f2": @(RETROK_F2),
            @"f3": @(RETROK_F3),
            @"f4": @(RETROK_F4),
            @"f5": @(RETROK_F5),
            @"f6": @(RETROK_F6),
            @"f7": @(RETROK_F7),
            @"f8": @(RETROK_F8),
            @"f9": @(RETROK_F9),
            @"f10": @(RETROK_F10),
            @"f11": @(RETROK_F11),
            @"f12": @(RETROK_F12),
            @"f13": @(RETROK_F13),
            @"f14": @(RETROK_F14),
            @"f15": @(RETROK_F15),
            @"escape": @(RETROK_ESCAPE),
            @"backspace": @(RETROK_BACKSPACE),
            @"tab": @(RETROK_TAB),
            @"return": @(RETROK_RETURN),
            @"space": @(RETROK_SPACE),
            @"delete": @(RETROK_DELETE),
            @"insert": @(RETROK_INSERT),
            @"home": @(RETROK_HOME),
            @"end": @(RETROK_END),
            @"pageup": @(RETROK_PAGEUP),
            @"pagedown": @(RETROK_PAGEDOWN),
            @"print": @(RETROK_PRINT),
            @"scrolllock": @(RETROK_SCROLLOCK),
            @"pause": @(RETROK_PAUSE),
            @"numlock": @(RETROK_NUMLOCK),
            @"capslock": @(RETROK_CAPSLOCK),
            @"up": @(RETROK_UP),
            @"down": @(RETROK_DOWN),
            @"left": @(RETROK_LEFT),
            @"right": @(RETROK_RIGHT),
            @"comma": @(RETROK_COMMA),
            @"period": @(RETROK_PERIOD),
            @"slash": @(RETROK_SLASH),
            @"semicolon": @(RETROK_SEMICOLON),
            @"quote": @(RETROK_QUOTE),
            @"leftbracket": @(RETROK_LEFTBRACKET),
            @"rightbracket": @(RETROK_RIGHTBRACKET),
            @"backslash": @(RETROK_BACKSLASH),
            @"minus": @(RETROK_MINUS),
            @"equals": @(RETROK_EQUALS),
            @"backquote": @(RETROK_BACKQUOTE),
            @"plus": @(RETROK_PLUS),
            @"asterisk": @(RETROK_ASTERISK),
            @"bar": @(RETROK_BAR),
            @"oem102": @(RETROK_OEM_102),
            @"shift": @(RETROK_LSHIFT),
            @"lshift": @(RETROK_LSHIFT),
            @"rshift": @(RETROK_RSHIFT),
            @"ctrl": @(RETROK_LCTRL),
            @"lctrl": @(RETROK_LCTRL),
            @"rctrl": @(RETROK_RCTRL),
            @"alt": @(RETROK_LALT),
            @"lalt": @(RETROK_LALT),
            @"ralt": @(RETROK_RALT),
            @"meta": @(RETROK_LMETA),
            @"lmeta": @(RETROK_LMETA),
            @"rmeta": @(RETROK_RMETA),
            @"kp0": @(RETROK_KP0),
            @"kp1": @(RETROK_KP1),
            @"kp2": @(RETROK_KP2),
            @"kp3": @(RETROK_KP3),
            @"kp4": @(RETROK_KP4),
            @"kp5": @(RETROK_KP5),
            @"kp6": @(RETROK_KP6),
            @"kp7": @(RETROK_KP7),
            @"kp8": @(RETROK_KP8),
            @"kp9": @(RETROK_KP9),
            @"kpperiod": @(RETROK_KP_PERIOD),
            @"kpdivide": @(RETROK_KP_DIVIDE),
            @"kpmultiply": @(RETROK_KP_MULTIPLY),
            @"kpminus": @(RETROK_KP_MINUS),
            @"kpplus": @(RETROK_KP_PLUS),
            @"kpenter": @(RETROK_KP_ENTER),
            @"kpequals": @(RETROK_KP_EQUALS),
            // Legacy KeyboardGameController names and character aliases.
            @"capsLock": @(RETROK_CAPSLOCK),
            @"control": @(RETROK_LCTRL),
            @"option": @(RETROK_LALT),
            @"command": @(RETROK_LMETA),
            @",": @(RETROK_COMMA),
            @".": @(RETROK_PERIOD),
            @"/": @(RETROK_SLASH),
            @";": @(RETROK_SEMICOLON),
            @"'": @(RETROK_QUOTE),
            @"[": @(RETROK_LEFTBRACKET),
            @"]": @(RETROK_RIGHTBRACKET),
            @"\\": @(RETROK_BACKSLASH),
            @"-": @(RETROK_MINUS),
            @"=": @(RETROK_EQUALS),
            @"`": @(RETROK_BACKQUOTE),
            @"+": @(RETROK_PLUS),
            @"*": @(RETROK_ASTERISK),
            @"|": @(RETROK_BAR)
        };
    });
    return map;
}

+ (instancetype)createCodeWithLabel:(NSString *)label code:(unsigned)code {
    LibretroKeyboardCode *keyboardCode = [LibretroKeyboardCode new];
    keyboardCode.label = label;
    keyboardCode.code = code;
    return keyboardCode;
}

+ (LibretroKeyboardCode *_Nullable)createCodeWithLabel:(NSString *_Nonnull)label {
    NSNumber *code = [self codeMap][label];
    if (!code) { return nil; }
    return [self createCodeWithLabel:label code:code.unsignedIntValue];
}

@end
